apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: bm17170wq-dotnet-basic
  janus-idp.io/tekton: bm17170wq-dotnet-basic
  backstage.io/kubernetes-id: bm17170wq-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: bm17170wq-dotnet-basic
resources:
- deployment.yaml
- route.yaml
- service.yaml
