apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: bm17170wq-dotnet-basic
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: bm17170wq-dotnet-basic 
  name: bm17170wq-dotnet-basic
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: bm17170wq-dotnet-basic
    weight: 100 
